#
metasheet: './matrix.csv'
ref: './ref.yaml'

# {'salmon', 'STAR'}
aligner: 'salmon'

# {'mm10', 'hg38'}
assembly: 'mm10'


#
samples:
  sample1:
    - data/sample1.fastq.gz
  sample2:
    - data/sample2.fastq.gz