#
metasheet: './metasheet.csv'
ref: './ref.yaml'

# {'salmon', 'STAR'}
aligner: 'salmon'

# {'mm10', 'hg38'}
assembly: 'mm10'

# {True, False}
trim: True

lisa: True

# if check_compare is False, DEAP will only align samples that have enough replications for saving time
# either will still trim and align samples but no different expression.
check_compare: False

#
samples:
  GSM2365762:
    - data/RS_PE/GSM2365762_R1.fastq.gz
    - data/RS_PE/GSM2365762_R2.fastq.gz
  GSM2365765:
    - data/RS_PE/GSM2365765_R1.fastq.gz
    - data/RS_PE/GSM2365765_R2.fastq.gz
  GSM2365766:
    - data/RS_PE/GSM2365766reads1.fastq.gz
    - data/RS_PE/GSM2365766reads2.fastq.gz
  GSM2309812:
    - data/RS_SE/GSM2309812.fastq.gz
  GSM2309813:
    - data/RS_SE/GSM2309813.fastq.gz
  GSM2309815:
    - data/RS_SE/GSM2309815.fastq.gz
  GSM2309818:
    - data/RS_SE/GSM2309818.fastq.gz
  MA_O:
    - data/MA/GSE41867_RAW
  MA_A:
    - data/MA/GSE12056_RAW
  GSM2067916:
    - data/GSE7138/GSM2067916.fastq.gz
  GSM2067917:
    - data/GSE7138/GSM2067917.fastq.gz
  GSM2067918:
    - data/GSE7138/GSM2067918.fastq.gz
  GSM2067919:
    - data/GSE7138/GSM2067919.fastq.gz


