name: DEAP
channels:
- bioconda
- conda-forge
- defaults

dependencies:
#GENERAL
- snakemake=5.4.5
- samtools
- python>=3.5.2
- r>=3.4.1

#align_STAR.snakefile
- star>=2.5.3a
- star-fusion=0.5.4
- bioconductor-sva

#DE.snakefile
- bioconductor-deseq2>=1.12.1
- bioconductor-limma
- bioconductor-edger
- bioconductor-tximport
- bioconductor-org.Hs.eg.db
- bioconductor-org.Mm.eg.db
- r-readr
- r-calibrate

#gsea.snakefile
- bioconductor-clusterprofiler

